//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robotvisionsystem
{
    [Serializable]
    public class RayMsg : Message
    {
        public const string k_RosMessageName = "robotvisionsystem_msgs/Ray";
        public override string RosMessageName => k_RosMessageName;

        public float[] ray_array;

        public RayMsg()
        {
            this.ray_array = new float[12];
        }

        public RayMsg(float[] ray_array)
        {
            this.ray_array = ray_array;
        }

        public static RayMsg Deserialize(MessageDeserializer deserializer) => new RayMsg(deserializer);

        private RayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ray_array, sizeof(float), 12);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ray_array);
        }

        public override string ToString()
        {
            return "RayMsg: " +
            "\nray_array: " + System.String.Join(", ", ray_array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
